services:
  db:
    ports:
      - "5432:5432"
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  web:
    depends_on:
      - db
    ports:
      - "5001:5001"
    image: yauhenii/nussknacker:0.1