[default]
    [default.uvicorn]
        APP = 'api:app'
        HOST = 'localhost'
        PORT = 5001
        LOG_LEVEL = 'info'
        RELOAD = true
    [default.logging]
        LOG_CONFIG_PATH = 'app/logger/log_conf.yaml'
    [default.db]
        PORT=5432
        HOST='database'
        TABLE_ENTITY_NAME='nussknacker.entity'
        