[default]
    [default.uvicorn]
        APP = 'api:app'
        HOST = '127.0.0.1'
        PORT = 5001
        LOG_LEVEL = 'info'
        RELOAD = true
    [default.logging]
        LOG_CONFIG_PATH = 'app/logger/log_conf.yaml'
        